const actionTypes = {
  GAME_STATUS: 'GAME_STATUS',
  SET_USERNAME: 'SET_USERNAME',
  SELECT_SHIP: 'SELECT_SHIP',
  DECREASE_SHIP_AMOUNT: 'DECREASE_SHIP_AMOUNT',
  SET_SHIPS_AVAIBLES: 'SET_SHIPS_AVAIBLES',
  CHANGE_TURN: 'CHANGE_TURN',
};

export default actionTypes;
